
# This file is automatically generated, you probably don't want to edit this

proximityOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "proximityOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            label = NULL,
            disSim = "clcDis",
            btwDir = "btwSbj",
            lvlMsr = "lvlInt",
            intDis = "intEuc",
            intSim = "intCrr",
            intPwr = 2,
            intRot = 2, ...) {

            super$initialize(
                package='PartialProximity',
                name='proximity',
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars)
            private$..label <- jmvcore::OptionVariable$new(
                "label",
                label)
            private$..disSim <- jmvcore::OptionList$new(
                "disSim",
                disSim,
                options=list(
                    "clcDis",
                    "clcSim"),
                default="clcDis")
            private$..btwDir <- jmvcore::OptionList$new(
                "btwDir",
                btwDir,
                options=list(
                    "btwSbj",
                    "btwVar"),
                default="btwSbj")
            private$..lvlMsr <- jmvcore::OptionList$new(
                "lvlMsr",
                lvlMsr,
                options=list(
                    "lvlInt",
                    "lvlBin",
                    "lvlCnt"),
                default="lvlInt")
            private$..intDis <- jmvcore::OptionList$new(
                "intDis",
                intDis,
                options=list(
                    "intEuc",
                    "intSqE",
                    "intChb",
                    "intBlk",
                    "intMnk",
                    "intCst"),
                default="intEuc")
            private$..intSim <- jmvcore::OptionList$new(
                "intSim",
                intSim,
                options=list(
                    "intCrr",
                    "intCos"),
                default="intCrr")
            private$..intPwr <- jmvcore::OptionInteger$new(
                "intPwr",
                intPwr,
                default=2,
                min=1,
                max=4)
            private$..intRot <- jmvcore::OptionInteger$new(
                "intRot",
                intRot,
                default=2,
                min=1,
                max=4)

            self$.addOption(private$..vars)
            self$.addOption(private$..label)
            self$.addOption(private$..disSim)
            self$.addOption(private$..btwDir)
            self$.addOption(private$..lvlMsr)
            self$.addOption(private$..intDis)
            self$.addOption(private$..intSim)
            self$.addOption(private$..intPwr)
            self$.addOption(private$..intRot)
        }),
    active = list(
        vars = function() private$..vars$value,
        label = function() private$..label$value,
        disSim = function() private$..disSim$value,
        btwDir = function() private$..btwDir$value,
        lvlMsr = function() private$..lvlMsr$value,
        intDis = function() private$..intDis$value,
        intSim = function() private$..intSim$value,
        intPwr = function() private$..intPwr$value,
        intRot = function() private$..intRot$value),
    private = list(
        ..vars = NA,
        ..label = NA,
        ..disSim = NA,
        ..btwDir = NA,
        ..lvlMsr = NA,
        ..intDis = NA,
        ..intSim = NA,
        ..intPwr = NA,
        ..intRot = NA)
)

proximityResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Distances")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Distances"))}))

proximityBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "proximityBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'PartialProximity',
                name = 'proximity',
                version = c(1,0,0),
                options = options,
                results = proximityResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Distances
#'
#' 
#' @param data .
#' @param vars .
#' @param label .
#' @param disSim .
#' @param btwDir .
#' @param lvlMsr .
#' @param intDis .
#' @param intSim .
#' @param intPwr .
#' @param intRot .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
proximity <- function(
    data,
    vars,
    label,
    disSim = "clcDis",
    btwDir = "btwSbj",
    lvlMsr = "lvlInt",
    intDis = "intEuc",
    intSim = "intCrr",
    intPwr = 2,
    intRot = 2) {

    if ( ! requireNamespace('jmvcore'))
        stop('proximity requires jmvcore to be installed (restart may be required)')

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(label)) label <- jmvcore::resolveQuo(jmvcore::enquo(label))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(label), label, NULL))


    options <- proximityOptions$new(
        vars = vars,
        label = label,
        disSim = disSim,
        btwDir = btwDir,
        lvlMsr = lvlMsr,
        intDis = intDis,
        intSim = intSim,
        intPwr = intPwr,
        intRot = intRot)

    analysis <- proximityClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
