
# This file is automatically generated, you probably don't want to edit this

proximityOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "proximityOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            label = NULL, ...) {

            super$initialize(
                package='PartialProximity',
                name='proximity',
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars)
            private$..label <- jmvcore::OptionVariable$new(
                "label",
                label)

            self$.addOption(private$..vars)
            self$.addOption(private$..label)
        }),
    active = list(
        vars = function() private$..vars$value,
        label = function() private$..label$value),
    private = list(
        ..vars = NA,
        ..label = NA)
)

proximityResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Distances")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Distances"))}))

proximityBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "proximityBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'PartialProximity',
                name = 'proximity',
                version = c(1,0,0),
                options = options,
                results = proximityResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Distances
#'
#' 
#' @param data .
#' @param vars .
#' @param label .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
proximity <- function(
    data,
    vars,
    label) {

    if ( ! requireNamespace('jmvcore'))
        stop('proximity requires jmvcore to be installed (restart may be required)')

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(label)) label <- jmvcore::resolveQuo(jmvcore::enquo(label))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(label), label, NULL))


    options <- proximityOptions$new(
        vars = vars,
        label = label)

    analysis <- proximityClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
